= ${var['title']}

// END-OF-HEADER. DO NOT MODIFY OR DELETE THIS LINE

++++
<!-- PAGE CATEGORY SCOPE TYPES TAB HEADER :: START -->
${var['header']}
<!-- PAGE CATEGORY SCOPE TYPES TAB HEADER :: END -->

<!-- PAGE CATEGORY CONTENT :: START -->
${var['content']}
<!-- PAGE CATEGORY CONTENT :: END -->
++++

