== About KB4IT

=== Introduction

_KB4IT_ is a static website generator based on Asciidoctor sources
mainly for technical documentation purposes.

You can see some demos here: https://github.com/t00m/kb4it-adocs

=== Motivations

* The main aim is to provide an easy way to write my technical
documentation.
* Don't care about the formatting and focus on the contents.
* To allow teams to manage their knowledge database easily.
* Do not depend on third software products like word processors or
complex web applications.

=== Features

==== Pros

* Writing documentation: Documents must be in Asciidoctor format which
is easy to learn.
* Finding documents: Once a document is converted to html, properties
can be browsed. Moreover, property pages have filters and a search entry
to filter by title.
* Publishing your repository: all necessary files are inside a
directory. Browse it or copy it to your web server.
* Serverless: There is no need for a web server. Of course, you can use
one if you please.
* Smart compiling: Only those documents added or modified are compiled.
* Use the default themes or build your own custom theme
* By modifying templates, it might be integrated with Github or Gitlab.

==== Cons

* Not to much documentation at this moment
* No online editor: At this moment, KB4IT doesn't include any online
editor. You must create or edit your documents with your preferred
editor.
* No dynamic search: KB4IT was developed to be as simple as possible.
* No dependencies at all excepting Asciidoctor (as text processor and
publishing toolchain) and Python (the programming language used).
* API is not stable
* Most of the requirements are tailored to my own necessities which
might not be the same as yours.

=== Installation

==== From source

If you have used this app before, it might be necessary to uninstall it
before:

`pip3 uninstall kb4it -qy`

Then, install it:

`pip install . --user`


==== Pypi package

`pip3 install kb4it --user -U`



=== Execution

=== Prepare your repository

. Create a repository: `mkdir /home/$USER/Documents/myrepo`
. Create config directory (where the configuration will be stored): `mkdir /home/$USER/Documents/myrepo/config`
. Create source directory (where the documents will be stored): `mkdir /home/$USER/Documents/myrepo/target`
. Create target directory (where the website will built): `mkdir /home/$USER/Documents/myrepo/target`
. Setup repository configuration: `kb4it -init techdoc /home/$USER/Documents/myrepo/config`
+
This will copy theme directory structure example to your repository. It will also create a script to generate the website. 
The directory structure is just an example. It can be modified.
. Finally, compile your repository: `kb4it -r /home/$USER/Documents/myrepo/config/repo.json`
+
_(See kb4it -v for more options)_


=== Known bugs

* Setup repository configuration: *not implemented yet*. Copy example file manually and edit it.
* When a document or any of its properties is modified, the document will be recompiled. However, those property pages linking to this document will display the original title. The only workaround right now pass by forcing KB4IT to recompile the whole repository with the `-f` option.


=== Download

Get the code from Github: https://github.com/t00m/KB4IT

`git clone https://github.com/t00m/KB4IT`

=== Credits

* http://www.python.org/[Python] Programming language that lets you work
more quickly and integrate your systems more effectively.
* https://asciidoctor.org[Asciidoctor] A fast text processor &
publishing toolchain for converting AsciiDoc to HTML5, DocBook & more.
* https://getuikit.com[UIKit] A lightweight and modular front-end
framework for developing fast and powerful web interfaces.
* https://www.geany.org/[Geany] Powerful, stable and lightweight
programmer's text editor that provides tons of useful features without
bogging down your workflow. It runs on Linux, Windows and MacOS is
translated into over 40 languages, and has built-in support for more
than 50 programming languages.

=== Contact

Tomás Vírseda (aka t00m): tomasvirseda@gmail.com

_I would appreciate to hear from your comments._
