= Extend Oracle tablespaces
:Author:        Nora Hobbs
:Category:      Procedure
:Status:        Released
:Scope:         Database Administration
:Team:          DBA
:Tag:           extend, tablespace, datafile
:Command:       brtools, brspace, sqlplus
:Tablespace:    PSAPSR3
:Database:      Oracle

// END-OF-HEADER. DO NOT MODIFY OR DELETE THIS LINE

== Extending a tablespace


=== with SQLPlus

Check if datafile directory exists. If not, create it with `ora<sid>`.


Then, create new datafile in the given tablespace:

----
alter tablespace PSAPSR3 add datafile '/oracle/DEV/sapdata2/sr3_8/sr3.data8' size 1000M autoextend on next 100 maxsize 10000M;
----



=== with BRTOOLS

menu:brtools[Space management > Extend tablespace]

====

oradev> brtools
BR0651I BRTOOLS 7.20 (38)

BR0280I BRTOOLS time stamp: 2009-07-19 15.56.49
BR0656I Choice menu 1 - please make a selection

BR*Tools main menu

 1 = Instance management
 2 - Space management
 3 - Segment management
 4 - Backup and database copy
 5 - Restore and recovery
 6 - Check and verification
 7 - Database statistics
 8 - Additional functions
 9 - Exit program

Standard keys: c - cont, b - back, s - stop, r - refr, h - help

BR0662I Enter your choice:
2
BR0280I BRTOOLS time stamp: 2009-07-19 15.56.51
BR0663I Your choice: '2'

BR0280I BRTOOLS time stamp: 2009-07-19 15.56.51
BR0656I Choice menu 5 - please make a selection

Database space management

 1 = Extend tablespace
 2 - Create tablespace
 3 - Drop tablespace
 4 - Alter tablespace
 5 - Alter data file
 6 - Move data file
 7 - Additional space functions
 8 - Reset program status

Standard keys: c - cont, b - back, s - stop, r - refr, h - help

BR0662I Enter your choice:
1
BR0280I BRTOOLS time stamp: 2009-07-19 15.56.53
BR0663I Your choice: '1'

BR0280I BRTOOLS time stamp: 2009-07-19 15.56.53
BR0657I Input menu 81 - please enter/check input values

BRSPACE options for tablespace extension

 1 - BRSPACE profile (profile) ...... [initDEV.sap]
 2 - Database user/password (user) .. [/]
 3 ~ Tablespace name (tablespace) ... []
 4 - Confirmation mode (confirm) .... [yes]
 5 - Scrolling line count (scroll) .. [20]
 6 - Message language (language) .... [E]
 7 - BRSPACE command line (command) . [-p initDEV.sap -s 20 -l E -f tsextend]

Standard keys: c - cont, b - back, s - stop, r - refr, h - help

BR0662I Enter your choice:
3
BR0280I BRTOOLS time stamp: 2009-07-19 15.56.57
BR0663I Your choice: '3'
BR0681I Enter string value for "tablespace" []:
PSAPSR3
BR0280I BRTOOLS time stamp: 2009-07-19 15.57.01
BR0683I New value for "tablespace": 'PSAPSR3'

BR0280I BRTOOLS time stamp: 2009-07-19 15.57.01
BR0657I Input menu 81 - please enter/check input values

BRSPACE options for tablespace extension

 1 - BRSPACE profile (profile) ...... [initDEV.sap]
 2 - Database user/password (user) .. [/]
 3 ~ Tablespace name (tablespace) ... [PSAPSR3]
 4 - Confirmation mode (confirm) .... [yes]
 5 - Scrolling line count (scroll) .. [20]
 6 - Message language (language) .... [E]
 7 - BRSPACE command line (command) . [-p initDEV.sap -s 20 -l E -f tsextend -t PSAPSR3]

Standard keys: c - cont, b - back, s - stop, r - refr, h - help

BR0662I Enter your choice:
c
BR0280I BRTOOLS time stamp: 2009-07-19 15.57.16
BR0663I Your choice: 'c'
BR0259I Program execution will be continued...

BR0291I BRSPACE will be started with options '-p initDEV.sap -s 20 -l E -f tsextend -t PSAPSR3'

BR0280I BRTOOLS time stamp: 2009-07-19 15.57.16
BR0670I Enter 'c[ont]' to continue, 'b[ack]' to go back, 's[top]' to abort:
c
BR0280I BRTOOLS time stamp: 2009-07-19 15.57.20
BR0257I Your reply: 'c'
BR0259I Program execution will be continued...

###############################################################################

BR1001I BRSPACE 7.20 (38)
BR1002I Start of BRSPACE processing: seyymuzg.tse 2009-07-19 15.57.20
BR0484I BRSPACE log file: /oracle/DEV/sapreorg/seyymuzg.tse

BR0280I BRSPACE time stamp: 2009-07-19 15.57.21
BR1009I Name of database instance: DEV
BR1010I BRSPACE action ID: seyymuzg
BR1011I BRSPACE function ID: tse
BR1012I BRSPACE function: tsextend

BR0280I BRSPACE time stamp: 2009-07-19 15.57.22
BR0657I Input menu 303 - please enter/check input values

Options for extension of tablespace PSAPSR3 (1. file)

 1 * Last added file name (lastfile) ....... [/oracle/DEV/sapdata2/sr3_6/sr3.data6]
 2 * Last added file size in MB (lastsize) . [10000]
 3 - New file to be added (file) ........... [/oracle/DEV/sapdata2/sr3_7/sr3.data7]
 4 ~ Raw disk / link target (rawlink) ...... []
 5 - Size of the new file in MB (size) ..... [10000]
 6 - File autoextend mode (autoextend) ..... [no]
 7 # Maximum file size in MB (maxsize) ..... []
 8 # File increment size in MB (incrsize) .. []
 9 - SQL command (command) ................. [alter tablespace PSAPSR3 add datafile '/oracle/DEV/sapdata2/sr3_7/sr3.data7' size 10000M autoextend off]

Standard keys: c - cont, b - back, s - stop, r - refr, h - help

BR0662I Enter your choice:
c
BR0280I BRSPACE time stamp: 2009-07-19 15.57.55
BR0663I Your choice: 'c'
BR0259I Program execution will be continued...

BR1091I Next data file can be specified now

BR0280I BRSPACE time stamp: 2009-07-19 15.57.55
BR0675I This is a optional action - do you want to execute it now?
BR0676I Enter 'y[es]' to execute the action, 'n[o]/c[ont]' to skip it, 's[top]' to abort:
no
BR0280I BRSPACE time stamp: 2009-07-19 15.58.02
BR0257I Your reply: 'no'
BR0678I The action will be skipped...

BR0370I Directory /oracle/DEV/sapreorg/seyymuzg created

BR0280I BRSPACE time stamp: 2009-07-19 15.58.02
BR0319I Control file copy created: /oracle/DEV/sapreorg/seyymuzg/cntrlDEV.old 15810560

BR0370I Directory /oracle/DEV/sapdata2/sr3_7 created

BR0280I BRSPACE time stamp: 2009-07-19 15.58.02
BR1088I Extending tablespace PSAPSR3 ...

BR0280I BRSPACE time stamp: 2009-07-19 15.58.27
BR1016I SQL statement 'alter tablespace PSAPSR3 add datafile '/oracle/DEV/sapdata2/sr3_7/sr3.data7' size 10000M autoextend off' executed successfully

BR1051I Tablespace PSAPSR3 extended successfully with file: /oracle/DEV/sapdata2/sr3_7/sr3.data7 10000M

BR0280I BRSPACE time stamp: 2009-07-19 15.58.27
BR0340I Switching to the next online redolog file for database instance DEV ...
BR0321I Switch to the next online redolog file for database instance DEV successful

BR0280I BRSPACE time stamp: 2009-07-19 15.58.28
BR0319I Control file copy created: /oracle/DEV/sapreorg/seyymuzg/cntrlDEV.new 15810560


====

