= How to write technical documentation
:Author:        t00mlabs
:Revnumber:     v0.2
:Revdate:       2018-09-05
:Category:      Procedure
:Status:        Draft
:Scope:         Documentation
:Department:
:Team:
:Tag:           help, asciidoctor, markdown, write, technical, documentation
:Priority:      High

// END-OF-HEADER. DO NOT MODIFY OR DELETE THIS LINE

== Introduction

This document explains how to write a document.

A KB4IT document (asciidoc document) have two sections:

. the header
. the body

== KB4IT document structure

=== Header

==== Core properties

All documents *must have* a header such as:

----
 = How to write technical documentation
 :Author:        t00mlabs
 :Revnumber:     v0.1
 :Revdate:       2018-07-27
 :Category:      Help
 :Status:        Draft
 :Scope:         Documentation
 :Department:
 :Team:
 :Tag:           help, asciidoctor, markdown, write, technical, documentation

 // END-OF-HEADER. DO NOT MODIFY OR DELETE THIS LINE
----

[IMPORTANT]
====
Do NOT forget to add the END-OF-HEADER comment
====

==== Other attributes

Along the core properties/attributes you can add others which suit to your documentation.

As an example, I've added the attribute *Priority*


=== Body

In the body section you can write what you want just like any other asciidoc document.

Take a look to the https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference] to get a better idea about how to write documents.

Or better, *check the source* of other documents in this repository or *use them as a template for yours*.

[TIP]
====
All compiled documents have a link at the end of header to the source document.

In this way, you can duplicate documents easily without spending too much time.
====

