name: check-kb4it-version

on:
  push:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version-file: .python-version

      - name: Install KB4IT
        run: uv tool install .

      - name: Run kb4it
        run: kb4it --version
